// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Program.cs.models;

#nullable disable

namespace Program.cs.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20241112105215_Init01")]
    partial class Init01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Program.cs.models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("StreetName")
                        .HasColumnType("int");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<int>("TownName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Program.cs.models.Person", b =>
                {
                    b.Property<int>("EGN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EGN"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proffession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EGN");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Program.cs.models.PersonShop", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("ShopId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonShop");
                });

            modelBuilder.Entity("Program.cs.models.Purpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Purpose");
                });

            modelBuilder.Entity("Program.cs.models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("EndHour")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int>("PurposeId")
                        .HasColumnType("int");

                    b.Property<int>("StartHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PurposeId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Program.cs.models.PersonShop", b =>
                {
                    b.HasOne("Program.cs.models.Person", "Person")
                        .WithMany("PersonShops")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Program.cs.models.Shop", "Shop")
                        .WithMany("ShopPeople")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Program.cs.models.Shop", b =>
                {
                    b.HasOne("Program.cs.models.Address", "Address")
                        .WithMany("Shops")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Program.cs.models.Purpose", "Purpose")
                        .WithMany("Shops")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("Program.cs.models.Address", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Program.cs.models.Person", b =>
                {
                    b.Navigation("PersonShops");
                });

            modelBuilder.Entity("Program.cs.models.Purpose", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Program.cs.models.Shop", b =>
                {
                    b.Navigation("ShopPeople");
                });
#pragma warning restore 612, 618
        }
    }
}
